#############################################################################
# Makefile for building: tvkaistagui
# Generated by qmake (2.01a) (Qt 4.6.2) on: ke tammi 12 13:10:15 2011
# Project:  tvkaista.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tvkaista.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"1.0.1\" -DTVKAISTAGUI_TRANSLATIONS_DIR=\"/usr/share/tvkaistagui/translations\" -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		tvkaistaclient.cpp \
		channelfeedparser.cpp \
		channel.cpp \
		programme.cpp \
		programmetableparser.cpp \
		htmlparser.cpp \
		cache.cpp \
		programmetablemodel.cpp \
		settingsdialog.cpp \
		downloader.cpp \
		downloadtablemodel.cpp \
		downloaddelegate.cpp \
		programmefeedparser.cpp \
		aboutdialog.cpp moc_mainwindow.cpp \
		moc_tvkaistaclient.cpp \
		moc_programmetablemodel.cpp \
		moc_settingsdialog.cpp \
		moc_downloader.cpp \
		moc_downloadtablemodel.cpp \
		moc_downloaddelegate.cpp \
		moc_aboutdialog.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		tvkaistaclient.o \
		channelfeedparser.o \
		channel.o \
		programme.o \
		programmetableparser.o \
		htmlparser.o \
		cache.o \
		programmetablemodel.o \
		settingsdialog.o \
		downloader.o \
		downloadtablemodel.o \
		downloaddelegate.o \
		programmefeedparser.o \
		aboutdialog.o \
		moc_mainwindow.o \
		moc_tvkaistaclient.o \
		moc_programmetablemodel.o \
		moc_settingsdialog.o \
		moc_downloader.o \
		moc_downloadtablemodel.o \
		moc_downloaddelegate.o \
		moc_aboutdialog.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tvkaista.pro
QMAKE_TARGET  = tvkaistagui
DESTDIR       = 
TARGET        = tvkaistagui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_settingsdialog.h ui_aboutdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tvkaista.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tvkaista.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile tvkaista.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tvkaistagui1.0.1 || $(MKDIR) .tmp/tvkaistagui1.0.1 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tvkaistagui1.0.1/ && $(COPY_FILE) --parents mainwindow.h tvkaistaclient.h channelfeedparser.h channel.h programme.h programmetableparser.h htmlparser.h cache.h programmetablemodel.h settingsdialog.h downloader.h downloadtablemodel.h downloaddelegate.h programmefeedparser.h aboutdialog.h .tmp/tvkaistagui1.0.1/ && $(COPY_FILE) --parents images.qrc .tmp/tvkaistagui1.0.1/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp tvkaistaclient.cpp channelfeedparser.cpp channel.cpp programme.cpp programmetableparser.cpp htmlparser.cpp cache.cpp programmetablemodel.cpp settingsdialog.cpp downloader.cpp downloadtablemodel.cpp downloaddelegate.cpp programmefeedparser.cpp aboutdialog.cpp .tmp/tvkaistagui1.0.1/ && $(COPY_FILE) --parents mainwindow.ui settingsdialog.ui aboutdialog.ui .tmp/tvkaistagui1.0.1/ && $(COPY_FILE) --parents translations/qt_fi.ts .tmp/tvkaistagui1.0.1/ && (cd `dirname .tmp/tvkaistagui1.0.1` && $(TAR) tvkaistagui1.0.1.tar tvkaistagui1.0.1 && $(COMPRESS) tvkaistagui1.0.1.tar) && $(MOVE) `dirname .tmp/tvkaistagui1.0.1`/tvkaistagui1.0.1.tar.gz . && $(DEL_FILE) -r .tmp/tvkaistagui1.0.1


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_tvkaistaclient.cpp moc_programmetablemodel.cpp moc_settingsdialog.cpp moc_downloader.cpp moc_downloadtablemodel.cpp moc_downloaddelegate.cpp moc_aboutdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_tvkaistaclient.cpp moc_programmetablemodel.cpp moc_settingsdialog.cpp moc_downloader.cpp moc_downloadtablemodel.cpp moc_downloaddelegate.cpp moc_aboutdialog.cpp
moc_mainwindow.cpp: channel.h \
		programme.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_tvkaistaclient.cpp: channel.h \
		programme.h \
		tvkaistaclient.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tvkaistaclient.h -o moc_tvkaistaclient.cpp

moc_programmetablemodel.cpp: programme.h \
		programmetablemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) programmetablemodel.h -o moc_programmetablemodel.cpp

moc_settingsdialog.cpp: settingsdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settingsdialog.h -o moc_settingsdialog.cpp

moc_downloader.cpp: downloader.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) downloader.h -o moc_downloader.cpp

moc_downloadtablemodel.cpp: programme.h \
		downloadtablemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) downloadtablemodel.h -o moc_downloadtablemodel.cpp

moc_downloaddelegate.cpp: downloaddelegate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) downloaddelegate.h -o moc_downloaddelegate.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/remove-22x22.png \
		images/preferences-16x16.png \
		images/go-previous-22x22.png \
		images/load-32x32.gif \
		images/multimedia-22x22.png \
		images/quit-16x16.png \
		images/stop-22x22.png \
		images/tvkaista-48x48.png \
		images/refresh-22x22.png \
		images/today-16x16.png \
		images/find-22x22.png \
		images/list-22x22.png \
		images/tvkaista-64x64.png \
		images/download-22x22.png \
		images/refresh-16x16.png \
		images/tvkaista-16x16.png \
		images/multimedia-16x16.png \
		images/play-22x22.png \
		images/go-next-22x22.png \
		images/go-previous-16x16.png \
		images/tvkaista-32x32.png \
		images/download-16x16.png \
		images/go-next-16x16.png
	/usr/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_settingsdialog.h ui_aboutdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_settingsdialog.h ui_aboutdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_settingsdialog.h: settingsdialog.ui
	/usr/bin/uic-qt4 settingsdialog.ui -o ui_settingsdialog.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/bin/uic-qt4 aboutdialog.ui -o ui_aboutdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		channel.h \
		programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp aboutdialog.h \
		cache.h \
		channel.h \
		programme.h \
		downloader.h \
		downloaddelegate.h \
		downloadtablemodel.h \
		programmetablemodel.h \
		tvkaistaclient.h \
		settingsdialog.h \
		mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tvkaistaclient.o: tvkaistaclient.cpp cache.h \
		channel.h \
		programme.h \
		channelfeedparser.h \
		programmefeedparser.h \
		programmetableparser.h \
		htmlparser.h \
		tvkaistaclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tvkaistaclient.o tvkaistaclient.cpp

channelfeedparser.o: channelfeedparser.cpp channelfeedparser.h \
		channel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelfeedparser.o channelfeedparser.cpp

channel.o: channel.cpp channel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channel.o channel.cpp

programme.o: programme.cpp programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o programme.o programme.cpp

programmetableparser.o: programmetableparser.cpp programmetableparser.h \
		htmlparser.h \
		programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o programmetableparser.o programmetableparser.cpp

htmlparser.o: htmlparser.cpp htmlparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o htmlparser.o htmlparser.cpp

cache.o: cache.cpp cache.h \
		channel.h \
		programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cache.o cache.cpp

programmetablemodel.o: programmetablemodel.cpp programmetablemodel.h \
		programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o programmetablemodel.o programmetablemodel.cpp

settingsdialog.o: settingsdialog.cpp mainwindow.h \
		channel.h \
		programme.h \
		settingsdialog.h \
		ui_settingsdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsdialog.o settingsdialog.cpp

downloader.o: downloader.cpp downloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloader.o downloader.cpp

downloadtablemodel.o: downloadtablemodel.cpp mainwindow.h \
		channel.h \
		programme.h \
		downloader.h \
		downloadtablemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloadtablemodel.o downloadtablemodel.cpp

downloaddelegate.o: downloaddelegate.cpp downloaddelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o downloaddelegate.o downloaddelegate.cpp

programmefeedparser.o: programmefeedparser.cpp programmefeedparser.h \
		programme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o programmefeedparser.o programmefeedparser.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tvkaistaclient.o: moc_tvkaistaclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tvkaistaclient.o moc_tvkaistaclient.cpp

moc_programmetablemodel.o: moc_programmetablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_programmetablemodel.o moc_programmetablemodel.cpp

moc_settingsdialog.o: moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsdialog.o moc_settingsdialog.cpp

moc_downloader.o: moc_downloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloader.o moc_downloader.cpp

moc_downloadtablemodel.o: moc_downloadtablemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloadtablemodel.o moc_downloadtablemodel.cpp

moc_downloaddelegate.o: moc_downloaddelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_downloaddelegate.o moc_downloaddelegate.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

